[[redirects]]
  from = "/netlify.app/aboutUs"
  to = "/aboutUs"
  status = 200

[[redirects]]
  from = "netlify.app/servicios"
  to = "/servicios"
  status = 200

[[redirects]]
  from = "netlify.app/contacto"
  to = "/contacto"
  status = 200

[[redirects]]
  from = "netlify.app/Certificados"
  to = "/Certificados"
  status = 200
